name: Clang-Format Check
# It is reccommended to test formatting locally before pushing to the repository.
# To do this, do the following:
# Install clang-format (if not already installed):
# sudo apt install clang-format
# Then, run the following command to check the formatting of all C++ files:
# find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)' -exec clang-format -i {} \;

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Run clang-format (Google style) check
        run: |
          SRC_FILES=$(find . -regex '.*\.\(cpp\|cc\|c\|h\|hpp\)' -not -path "./build/*")
          clang-format --dry-run --Werror $SRC_FILES